// | Category           | Operators                               | Names                                                                                                | Example                                                          |              |                 |
// | ------------------ | --------------------------------------- | ---------------------------------------------------------------------------------------------------- | ---------------------------------------------------------------- | ------------ | --------------- |
// | Arithmetic         | `+ , - , * , / , % , ** , ++ , --`      | Addition, Subtraction, Multiplication, Division, Modulus, Exponentiation, Increment, Decrement       | `5+2=7`, `x++`                                                   |              |                 |
// | Assignment         | `= , += , -= , *= , /= , %= , **=`      | Assign, Add assign, Subtract assign, Multiply assign, Divide assign, Modulus assign, Exponent assign | `x+=2`                                                           |              |                 |
// | Comparison         | `== , === , != , !== , > , < , >= , <=` | Equal, Strict equal, Not equal, Strict not equal, Greater, Less, Greater equal, Less equal           | `5=="5"`                                                         |              |                 |
// | Logical            | `&& ,                                   |                                                                                                      | , !`                                                             | AND, OR, NOT | `true && false` |
// | Bitwise            | `& ,                                    | , ^ , ~ , << , >> , >>>`                                                                             | AND, OR, XOR, NOT, Left shift, Right shift, Unsigned right shift | `5 & 1`      |                 |
// | String             | `+ , +=`                                | Concatenation, Concatenate assign                                                                    | `"a"+"b"`                                                        |              |                 |
// | Ternary            | `? :`                                   | Conditional operator                                                                                 | `age>18 ? "Yes":"No"`                                            |              |                 |
// | Type               | `typeof , instanceof`                   | Type check, Instance check                                                                           | `typeof "hi"`                                                    |              |                 |
// | Unary              | `+ , - , ++ , -- , !`                   | Unary plus, Unary minus, Increment, Decrement, NOT                                                   | `+"5"`                                                           |              |                 |
// | Relational         | `in , delete`                           | Property check, Delete property                                                                      | `"x" in obj`                                                     |              |                 |
// | Spread/Rest        | `...`                                   | Spread / Rest                                                                                        | `[...arr]`                                                       |              |                 |
// | Optional / Nullish | `?. , ??`                               | Optional chaining, Nullish coalescing                                                                | `user?.name`, `a ?? b`                                           |              |                 |
